# Generated by Django 3.1.7 on 2021-03-19 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
